name: Docker testing image
run-name: ${{ github.actor }} is testing the docker image

on:
  push:
    branches:
      - test
  pull_request:

jobs:
  test-image:
    name: Test docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build an image from Dockerfile
        run: sudo docker build --build-arg base="ros:foxy" -t turtlebotfoxy ./ros_master_foxy
      
      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: turtlebotfoxy
          exit-code: 0
          format: table
      

