name: Docker testing image
run-name: ${{ github.actor }} is testing the docker image

on:
  push:
    branches:
      - test
  pull_request:

jobs:
  test-image:
    name: Test docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build an image from Dockerfile
        run: sudo docker build --build-arg base="ros:foxy" -t turtlebotfoxy ./ros_master_foxy

      - name: Unit Testing in Docker
        run: |
          docker run --rm turtlebotfoxy 

      - name: Get Trivy CVES image analyse with securtiy vulnerability for the image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: turtlebotfoxy
          exit-code: 0
          format: table
      
      - name: Get High security vulnerability and export it !!!
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: turtlebotfoxy
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

